config/routes.rb
Kitten::Application.routes.draw do
  # login & logout
  get 'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  # a way to get some user data for the mta server
  post 'auth' => 'sessions#auth'

  # allow new people to register
  get 'signup' => 'users#new', :as => :signup
  post 'signup' => 'users#create'

  # user list
  resources :users, :only => [:show]

  resources :blogs, :path => '/blog', :constraints => { :blog_id => /\d[^\/]+/ } do
    post :comment
    constraints :comment_id => /[\d]+/ do
      get ':comment_id' => 'blogs#edit_comment', :as => 'edit_comment'
      put ':comment_id' => 'blogs#update_comment'
    end

    get 'page/:page', :on => :collection, :action => :index
    get 'page/:page', :on => :member, :action => :show

    # all not-post requests on comments are redirected to the blog post
    match 'comment' => redirect('/blog/%{blog_id}')
  end

  resources :forums, :only => [:index, :show], :path => '/community' do
    get 'page/:page', :on => :member, :action => :show
    collection do
      get :manage
      post :managed, :path => 'manage'
    end

    resources :topics, :only => [ :new, :create], :path => '/topic'
    constraints :id => /\d[^\/]+/ do
      get '/:id' => 'topics#show', :as => 'topic'
      get '/:id/page/:page' => 'topics#show'
      post '/:id' => 'topics#reply', :as => 'reply'
    end
  end

  # root
  root :to => 'sessions#new'
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :topics

  # tree structure
  has_ancestry :orphan_strategy => :restrict
  scope :roots, :conditions => { ancestry_column => nil }, :order => 'sort asc'
  def children
    self.base_class.scoped :conditions => child_conditions, :order => 'sort asc'
  end

  attr_accessible :name

  # fancy urls
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    authorize! :read, Forum
    @forums = Forum.roots
  end

  def show
    @forum = Forum.find(params[:id])
    authorize! :read, @forum
    @topics = @forum.topics.sorted.page params[:page]
  end

  def manage
    authorize! :manage, Forum
    @forums = Forum.roots
  end

  # saves the new forum order
  def managed
    authorize! :manage, Forum
    Forum.transaction do
      forums = Forum.all
      logger.info params[:forums]

      # set the new parents
      update_parents params[:forums], forums, nil

      # raise an exception if the data is bullshit
      logger.info 'Checking the integrity'
      Forum.check_ancestry_integrity!
    end

    # don't need no response here
    head :ok
  end

  private
  # updates the forums to match the new parent-ids
  #   updated: parameters for the individual forums to set, may have children to call recursively
  #   forums: list of all forums
  #   parent: new parent to set
  def update_parents updated, forums, parent
    updated.each_with_index do |forum, index|
      info = forum[1]
      if info[:id].to_i < 0
        # new forum!
        to_update = Forum.new({:name => info[:name]})
      else
        # find the forum with that id
        to_update = forums.select{ |f| f.id == info[:id].to_i }.first
      end
      if to_update
        to_update.sort = index + 1
        to_update.category = info[:category] == 'true'

        # save the new parent
        to_update.parent = parent
        to_update.save!

        # update all children to have the just-updated forum as parent
        unless info[:children].nil?
          update_parents info[:children], forums, to_update
        end
      end
    end
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_forum.html.slim
- if forum.category?
  .category
    h2= forum.name
    - forum.children.each do |f|
      == render :partial => 'forumbit', :locals => { :forum => f }
- else
  == render :partial => 'forumbit', :locals => { :forum => forum }

app/views/forums/_forumbit.html.slim
.forumbit
  .title
    = link_to forum.name, forum
    - if forum.has_children?
      ul
        - forum.children.each do |f|
          li
            | &bull;&nbsp;
            = link_to f.name, f

app/views/forums/_manage_forum.html.slim
- forums.each do |forum|
  li id="forum_#{forum.id}" data-category=forum.category
    div class=(forum.category? ? 'category' : nil)
      span.actions
        = link_to '', '#', :class => 'icon-flag'
      = forum.name
    - if forum.has_children?
      ol
        == render :partial => 'manage_forum', :locals => { :forums => forum.children }

app/views/forums/_topic.html.slim
.topicbit
  .title
    .author
      = link_to topic.user do
        img src=topic.user.avatar_small title=topic.user.name
    = link_to topic.title, [@forum, topic]

app/views/forums/index.html.slim
- content_for :head do
  - if can? :manage, Forum
    .actions
      = link_to 'Manage', manage_forums_path
  h1 Community
.forum
  - @forums.each do |forum|
    == render :partial => 'forum', :locals => { :forum => forum }

app/views/forums/manage.html.slim
- content_for :header do
  = javascript_include_tag 'jquery.ui'
  = javascript_include_tag 'jquery.mjs.nestedSortable'

- content_for :head do
  .actions
    = link_to 'Save', '#', :class => 'save'
  h1 Manage Forums

.manageforums
  ol#sortable
    == render :partial => 'manage_forum', :locals => { :forums => @forums }
  hr
  = link_to 'New', '#', :class => 'newforum'
  javascript:
    $(document).ready(function(){
      $('#sortable').nestedSortable({
        handle: 'div',
        items: 'li',
        toleranceElement: '> div',
        expression: /(.+)[_](.+)/,
        collectAttributes: function(o) {
          return {name: o.attr('name'), category: o.attr('data-category') ? true : false}
        }
      });
    });
    $('.save').click(function() {
      var data = { forums: $('#sortable').nestedSortable('toHierarchy') };
      $.ajax({
        type: "POST",
        url: window.location.href + '.json',
        data: data
      }).always(function(e) {
        if(e.status == 200) {
          window.location.reload(true)
        } else {
          alert('Failed to update forums: ' + e.status + ': ' + e.statusText);
        }
      });
      return false;
    });

    // creates a new pseudo-forum
    var newforumindex = 0;
    $('.newforum').click(function() {
      var name = prompt('Name of the new Forum?')
      if(name && name.length > 0) {
        var li = $('<li></li>', {id: 'forum_' + --newforumindex, name: name});
        $('<div></div>', {text: name}).appendTo(li);
        li.appendTo('#sortable');
      }
      return false;
    });

    $('.icon-flag').click(function() {
      var div = $(this).parent().parent();
      var li = div.parent();
      div.toggleClass('category');
      if(div.hasClass('category')) {
        li.attr('data-category', 'data-category');
      } else {
        li.attr('data-category', null);
      }
      return false;
    });

app/views/forums/show.html.slim
- content_for :head do
  .returnto
    = link_to 'Community', forums_path
    - @forum.path.each do |parent|
      - unless parent == @forum
        = link_to parent.name, parent
  - if can? :create_topic, @forum
    .actions
      = link_to 'New Topic', new_forum_topic_path(@forum)
  h1= @forum.name

.forum.subforum
  / Ignore this if we are on a page other than the first
  - if not params[:page] and @forum.has_children?
    .category
      - @forum.children.each do |forum|
        == render :partial => 'forum', :locals => { :forum => forum }

  .topics
    - @topics.each do |topic|
      == render :partial => 'topic', :locals => { :topic => topic }
      = paginate @topics