config/routes.rb
Kitten::Application.routes.draw do
  # login & logout
  get 'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  # a way to get some user data for the mta server
  post 'auth' => 'sessions#auth'

  # allow new people to register
  get 'signup' => 'users#new', :as => :signup
  post 'signup' => 'users#create'

  # user list
  resources :users, :only => [:show]

  resources :blogs, :path => '/blog', :constraints => { :blog_id => /\d[^\/]+/ } do
    post :comment
    constraints :comment_id => /[\d]+/ do
      get ':comment_id' => 'blogs#edit_comment', :as => 'edit_comment'
      put ':comment_id' => 'blogs#update_comment'
    end

    get 'page/:page', :on => :collection, :action => :index
    get 'page/:page', :on => :member, :action => :show

    # all not-post requests on comments are redirected to the blog post
    match 'comment' => redirect('/blog/%{blog_id}')
  end

  resources :forums, :only => [:index, :show], :path => '/community' do
    get 'page/:page', :on => :member, :action => :show
    collection do
      get :manage
      post :managed, :path => 'manage'
    end

    resources :topics, :only => [ :new, :create], :path => '/topic'
    constraints :id => /\d[^\/]+/ do
      get '/:id' => 'topics#show', :as => 'topic'
      get '/:id/page/:page' => 'topics#show'
      post '/:id' => 'topics#reply', :as => 'reply'
    end
  end

  # root
  root :to => 'sessions#new'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  paginates_per 3 # blog posts on the /blog page

  belongs_to :user
  has_many :comments, :as => :commentable

  scope :sorted, order('created_at desc, id desc')

  attr_accessible :text, :title

  validates :title, :presence => true
  validates :text, :presence => true
  validates :user, :presence => true

  has_formatted :text

  # nicer urls
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :load_blog, :except => [:index, :new, :create]
  before_filter :load_comment, :only => [:edit_comment, :update_comment]

  def index
    authorize! :read, Blog
    @blogs = Blog.sorted.page params[:page]

    respond_to do |format|
      format.html
      format.json { render :json => @blogs, :only => [:id, :title, :text, :created_at], :include => {:user => {:only => [:id, :name]} } }
      format.rss { render :layout => false }
    end
  end

  def show
    authorize! :read, @blog
    @comments = @blog.comments.page params[:page]
    @comment = Comment.new
  end

  def new
    authorize! :create, Blog
    @blog = Blog.new
  end

  def create
    authorize! :create, Blog
    @blog = Blog.new(params[:blog])
    @blog.user = current_user
    logger.info current_user
    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    authorize! :update, @blog
  end

  def update
    authorize! :update, @blog

    if @blog.update_attributes(params[:blog])
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    authorize! :destroy, @blog
    @blog.destroy

    redirect_to blogs_url
  end

  def comment
    authorize! :comment, @blog
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.commentable = @blog
    if @comment.save
      redirect_to @blog, :anchor => "comment-#{@comment.id}"
    else
      render action: 'comment'
    end
  end

  def edit_comment
    authorize! :update, @comment
  end

  def update_comment
    authorize! :update, @comment

    if @comment.update_attributes(params[:comment])
      redirect_to @blog, notice: 'Comment was successfully updated.'
    else
      render action: "edit_comment"
    end
  end

  private
    def load_blog
      @blog = Blog.find(params[:blog_id] || params[:id])
    end

    def load_comment
      @comment = @blog.comments.find(params[:comment_id])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_comment.html.slim
.post.small id="comment-#{comment.id}"
  .author
    .avatar
      = link_to comment.user do
        img src=comment.user.avatar_small title=comment.user.name

  .pie
    - if can? :edit, comment
      = link_to 'Edit', blog_edit_comment_path(@blog, comment)
    span title=comment.created_at.to_s(:long_ordinal)
      = timely comment.created_at
  .ninja
    == comment.formatted_text

app/views/blogs/_comment_form.html.slim
= form_for comment, :url => url, :method => method do |f|
  .post.small
    .author
      .avatar
        img src=current_user.avatar_small title=current_user.name

    - if comment.errors.any?
      #error_explanation
        h2 = "#{pluralize(comment.errors.count, "error")} prohibited this comment from being saved:"
        ul
          - comment.errors.each do |field, message|
            li= comment.errors.full_message(field == :text ? :comment : field, message)
    .field
      = f.label :text, 'Comment'
      = f.text_area :text, :rows => 5
    .actions = f.submit method == :put ? 'Save' : 'Add Comment', :disable_with => method == :put ? 'Saving...' : 'Adding Comment...', :class => 'do'

app/views/blogs/_form.html.slim
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@blog.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @blog.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_area :text
  .actions = f.submit 'Save'

app/views/blogs/_show.html.slim
.post
  .author
    .avatar
      = link_to blog.user do
        img src=blog.user.avatar_large title=blog.user.name
    .name= link_to blog.user.name, blog.user
  .pie
    span title=blog.created_at.to_s(:long_ordinal)
      = timely blog.created_at
  - unless local_assigns[:hide_title]
    h2= link_to blog.title, blog
  .ninja
    == blog.formatted_text

app/views/blogs/comment.html.slim
- content_for :head do
  .thin
    .returnto
      = link_to 'Blog', blogs_path
      = link_to @blog.title, @blog
    h1 Comment

.thin.blog
  == render :partial => 'comment_form', :locals => { :comment => @comment, :url => blog_comment_path(@blog), :method => :post }

app/views/blogs/edit.html.slim
h1 Editing blog

== render 'form'

= link_to 'Show', @blog
'|
= link_to 'Back', blogs_path

app/views/blogs/edit_comment.html.slim
- content_for :head do
  .thin
    .returnto
      = link_to 'Blog', blogs_path
      = link_to @blog.title, @blog
    h1 'Edit Comment'

.thin.blog
  .comments
    == render :partial => 'comment_form', :locals => { :comment => @comment, :url => blog_edit_comment_path(@blog, @comment), :method => :put }

app/views/blogs/index.html.slim
- content_for :head do
  .thin
    - if can? :create, Blog
      .actions
        = link_to 'New', new_blog_path
    h1 Blog

.thin.blog
  - @blogs.each do |blog|
    == render :partial => 'show', :locals => { :blog => blog }
  = paginate @blogs

app/views/blogs/new.html.slim
h1 New blog

== render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.slim
- content_for :head do
  .thin
    .returnto= link_to 'Blog', blogs_path
    - if can?(:edit, @blog) || can?(:delete, @blog)
      .actions
        = link_to_if can?(:edit, @blog), 'Edit', edit_blog_path(@blog)
        = link_to_if can?(:delete, @blog), 'Delete', @blog, :confirm => 'Are you sure?', :method => :delete
    h1= @blog.title

.thin.blog
  == render :partial => 'show', :locals => { :blog => @blog, :hide_title => true }

  .comments
    - if @comments.count > 0
      h2= pluralize(@blog.comments.count, "Comment")
      - @comments.each do |comment|
        == render :partial => 'comment', :locals => { :comment => comment }
      = paginate @comments

    - if can? :comment, @blog
      h2 Comment
      == render :partial => 'comment_form', :locals => { :comment => @comment, :url => blog_comment_path(@blog), :method => :post }