config/routes.rb
Kitten::Application.routes.draw do
  # login & logout
  get 'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  # a way to get some user data for the mta server
  post 'auth' => 'sessions#auth'

  # allow new people to register
  get 'signup' => 'users#new', :as => :signup
  post 'signup' => 'users#create'

  # user list
  resources :users, :only => [:show]

  resources :blogs, :path => '/blog', :constraints => { :blog_id => /\d[^\/]+/ } do
    post :comment
    constraints :comment_id => /[\d]+/ do
      get ':comment_id' => 'blogs#edit_comment', :as => 'edit_comment'
      put ':comment_id' => 'blogs#update_comment'
    end

    get 'page/:page', :on => :collection, :action => :index
    get 'page/:page', :on => :member, :action => :show

    # all not-post requests on comments are redirected to the blog post
    match 'comment' => redirect('/blog/%{blog_id}')
  end

  resources :forums, :only => [:index, :show], :path => '/community' do
    get 'page/:page', :on => :member, :action => :show
    collection do
      get :manage
      post :managed, :path => 'manage'
    end

    resources :topics, :only => [ :new, :create], :path => '/topic'
    constraints :id => /\d[^\/]+/ do
      get '/:id' => 'topics#show', :as => 'topic'
      get '/:id/page/:page' => 'topics#show'
      post '/:id' => 'topics#reply', :as => 'reply'
    end
  end

  # root
  root :to => 'sessions#new'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  # TODO replace with last post time
  scope :sorted, order('created_at desc')

  belongs_to :user
  belongs_to :forum
  has_many :comments, :as => :commentable

  attr_accessible :title

  # virtual attribute text for creating comments
  attr_accessor :text
  attr_accessible :text

  validates :title, :presence => true
  validates :user, :presence => true
  validates :forum, :presence => true
  validates :text, :presence => { :on => :create }

  # fancy url
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :load_forum
  before_filter :load_topic, :except => [:new, :create]

  def new
    authorize! :create_topic, @forum
    @topic = @forum.topics.new
  end

  def create
    authorize! :create_topic, @forum
    @topic = @forum.topics.new(params[:topic])
    @topic.user = current_user
    Topic.transaction do
      begin
        @topic.save!

        # add a comment
        comment = @topic.comments.new
        comment.user = @topic.user
        comment.text = @topic.text
        comment.commentable = @topic
        comment.save!

        redirect_to [@forum, @topic]
      rescue
        render action: 'new'
      end
    end
  end

  def show
    @comments = @topic.comments.page params[:page]
    if can? :comment, @topic
      @newcomment = Comment.new
      @newcomment.user = current_user
    end
  end

  def reply
    authorize! :comment, @topic
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.commentable = @topic
    if @comment.save
      redirect_to [@forum, @topic], :anchor => "comment-#{@comment.id}"
    end
  end

  private
    def load_forum
      @forum = Forum.find(params[:forum_id])
      authorize! :read, @forum
    end

    def load_topic
      @topic =  @forum.topics.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_comment.html.slim
.post
  .author
    .avatar
      img src=comment.user.avatar_large title=comment.user.name
    .name= link_to comment.user.name, comment.user

  .pie
    span title=comment.created_at.to_s(:long_ordinal)
      = timely comment.created_at
  .ninja
    == comment.formatted_text

app/views/topics/_comment_form.html.slim
= form_for comment, :url => forum_reply_path(topic.forum, topic) do |f|
  .post
    .author
      .avatar
        img src=comment.user.avatar_large title=comment.user.name
      .name= link_to comment.user.name, comment.user
    - if comment.errors.any?
      #error_explanation
        h2 = "#{pluralize(comment.errors.count, "error")} prohibited this comment from being saved:"
        ul
          - comment.errors.full_messages.each do |message|
            li = message
    .field
      = f.label :text, 'Your Reply'
      = f.text_area :text, :rows => 5
    .actions
      - if cancel
        = link_to 'Cancel', [topic.forum, topic], :class => 'button floatleft', :confirm => 'Are you sure you want to discard your comment?'
      = f.submit 'Reply', :disable_with => 'Replying...', :class => 'do'

app/views/topics/create.html.slim
h1 Topics#create
p Find me in app/views/topics/create.html.slim

app/views/topics/new.html.slim
- content_for :head do
  .returnto
    = link_to @topic.forum.name, @topic.forum
  h1 New Topic

.topic.new
  .post
    .author
      .avatar
        img src=current_user.avatar_large title=current_user.name
      .name= link_to current_user.name, current_user
    = form_for @topic, :url => forum_topics_path(@topic.forum) do |f|
      - if @topic.errors.any?
        #error_explanation
          h2 = "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
          ul
            - @topic.errors.full_messages.each do |message|
              li = message
      .field
        = f.label :title, 'Title'
        = f.text_field :title
      .field
        = f.label :text, 'Text'
        = f.text_area :text
      .actions
        = submit_tag 'Create Topic', :disable_with => 'Creating Topic...', :class => 'do'

app/views/topics/reply.html.slim
- content_for :head do
  .returnto
    = link_to @topic.forum.name, @topic.forum
    = link_to @topic.title, [@topic.forum, @topic]
  h1 Reply

.topic
  .comments
    #new_comment
      == render :partial => 'comment_form', :locals => { :comment => @comment, :topic => @topic, :cancel => true }

app/views/topics/show.html.slim
- content_for :head do
  .returnto
    = link_to @topic.forum.name, @topic.forum
  h1= @topic.title

.topic
  .comments
    - @comments.each do |comment|
      == render :partial => 'comment', :locals => { :comment => comment }
    = paginate @comments

    - if can? :comment, @topic
      h2 Reply
      #new_comment
        == render :partial => 'comment_form', :locals => { :comment => @newcomment, :topic => @topic, :cancel => false }