config/routes.rb
Kitten::Application.routes.draw do
  # login & logout
  get 'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  # a way to get some user data for the mta server
  post 'auth' => 'sessions#auth'

  # allow new people to register
  get 'signup' => 'users#new', :as => :signup
  post 'signup' => 'users#create'

  # user list
  resources :users, :only => [:show]

  resources :blogs, :path => '/blog', :constraints => { :blog_id => /\d[^\/]+/ } do
    post :comment
    constraints :comment_id => /[\d]+/ do
      get ':comment_id' => 'blogs#edit_comment', :as => 'edit_comment'
      put ':comment_id' => 'blogs#update_comment'
    end

    get 'page/:page', :on => :collection, :action => :index
    get 'page/:page', :on => :member, :action => :show

    # all not-post requests on comments are redirected to the blog post
    match 'comment' => redirect('/blog/%{blog_id}')
  end

  resources :forums, :only => [:index, :show], :path => '/community' do
    get 'page/:page', :on => :member, :action => :show
    collection do
      get :manage
      post :managed, :path => 'manage'
    end

    resources :topics, :only => [ :new, :create], :path => '/topic'
    constraints :id => /\d[^\/]+/ do
      get '/:id' => 'topics#show', :as => 'topic'
      get '/:id/page/:page' => 'topics#show'
      post '/:id' => 'topics#reply', :as => 'reply'
    end
  end

  # root
  root :to => 'sessions#new'
end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title= "#{t('title1')} #{t('title2')}"
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'application'
    = auto_discovery_link_tag :rss, blogs_url(:rss), :title => 'Blog'
    link rel='icon' type='image/png' href='/favicon.png'
    = csrf_meta_tags
    = yield :header

  body
    header
      .container
        = link_to root_path do
          h1= image_tag('orange.png')
          h3
            strong= t('title1')
            = t('title2')
        nav
          ul
            li= link_to 'Blog', blogs_path, :class => nav_active?('blogs')
            li= link_to 'Community', forums_path, :class => nav_active?('forums', 'topics')
            li= link_to 'Wiki', '#'
            li= link_to 'Help', '#'
        nav.who
          ul
            - if current_user
              li= link_to current_user.name, current_user
              li= link_to 'Logout', logout_path, :method => :delete
            - else
              li= link_to 'Login', login_path, :class => nav_active?('sessions')
              li= link_to 'Sign up', signup_path, :class => nav_active?('users#new')
    - if content_for? :head
      .content-header
        .container
          = yield :head
    .container
      = yield
    footer &copy; #{Time.now.year} #{t('title1')} #{t('title2')}. All Rights reserved.